name: Python 應用程式

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 設置 Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: 安裝依賴
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
    - name: 運行測試
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        DATABASE_URL: sqlite:///instance/test.db
        SESSION_SECRET: test-session-secret
      run: |
        pytest -xvs 